### PR TITLE
[FIX] Empty dataframe initialization

### LINKED ISSUE #259: Issues with empty DataFrames
There are two cases that lead small issues relate to empty DataFrames:

#####  No arguments to `DataFrame`
```
> {DataFrame} = require("@rapidsai/cudf")

> const df = new DataFrame()
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at _seriesToColumns (/opt/node-rapids/modules/cudf/build/js/data_frame.js:31:41)
    at new DataFrame (/opt/node-rapids/modules/cudf/build/js/data_frame.js:95:110)
```
Presumably this should function identically to `new DataFrame({})`, which does work

##### `numRows` on empty `DataFrame`
```
> {DataFrame} = require("@rapidsai/cudf")

> new DataFrame({}).numRows 
Uncaught TypeError: Cannot read property 'length' of undefined
    at DataFrame.get numRows [as numRows] (/opt/node-rapids/modules/cudf/build/js/data_frame.js:112:54)
```
should return 0

### PR DESCRIPTION
**Pull request by mzegar**
I needed this fix for my current branch which uses an empty `dataframe`. I did a search for any other `columns[0]` accessing without checking length but couldn't find any others.

Closes #259

### CODE REVIEW

File: modules/cudf/src/data_frame.ts [hunk 1]
```diff
@@ -162,7 +162,7 @@ export class DataFrame<T extends TypeMap = any> {
    * df.numRows // 2
    * ```
    */
-  get numRows() { return this._accessor.columns[0].length; }
+  get numRows() { return this._accessor.columns.length > 0 ? this._accessor.columns[0].length : 0; }
```
Comment (mzegar) [inline modules/cudf/src/data_frame.ts:165]: Was also considering...
```js
return this._accessor.columns[0]?.length ?? 0;
```
But I think this is a bit more readable.

**Review by bryevdv — APPROVED** [review]

**Review by bryevdv — APPROVED** [review]
